server:
  port: 9095
spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://database.cusdxsftolnc.eu-north-1.rds.amazonaws.com:5432/notifications?ssl=false
    username: postgres
    password: '{cipher}b41da68bbefacb9256bfa2b4c5d7aa96bd350716018ae08edcb837d232f985c015215920e5944ae491803fe4bcc70f15'
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # use validate in production
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  sendgrid:
    api-key: test
profiles:
  url: http://localhost:8080
  brand-info-by-name: /api/v1/brands/by-name/{name}
  chech-if-user-blocked: /api/v1/{id}/check-if-block/{user_id}
find-chats: api/v1/user/find/brands
app:
  email:
    enabled: true
    default-email: "info@theinfluencers.com"
  push:
    enabled: true
logging:
  level:
    com.agenatech: DEBUG
springdoc.api-docs.path: /api/v1/notification-service/api-doc
management:
  endpoints:
    web:
      exposure:
        include: '*'
health:
  config:
    enabled: false
