server:
  port: 8081

security-constraints:
  open-uri:
    - /actuator/**
    - /api/v1/*/api-doc
    - /webjars/swagger-ui/**
    - /swagger-ui**
    - /v3/api-docs/**

cors:
  allowedOrigins: "*"
  allowedMethods: "*"
  allowedHeaders: "*"
  allowedCredentials: true
  maxAge: "3600"

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 7s
      forwarded:
        enabled: true
      x-forwarded:
        enabled: true
        forEnabled: true
        protoEnabled: true
        portEnabled: true
        prefixEnabled: true
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: false
      routes:
        - id: profilesPrincipal
          uri: http://localhost:8080
          predicates:
            - Path= /api/v1/access-request/**, /api/v1/access-request, /api/v1/brands/remove-premium, /api/v1/brands/make-premium, /api/v1/influencers/remove-premium, /api/v1/influencers/make-premium, /api/v1/advertising-pitch-type, /api/v1/advertising-pitch-type/**, /api/v1/influencers/me/access-request, /api/v1/influencers/me, /api/v1/influencers/me/followersCount, /api/v1/influencers/me/externalReferences, /api/v1/influencers/me/prices, /api/v1/influencers/me/prices/**, /api/v1/influencers/me/support, /api/v1/influencers/me/deals
            - Method=POST,GET,PUT,PATCH,DELETE
          filters:
            - AddPrincipalToPathFilter
        - id: profiles-brand
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/brands/me, /api/v1/brands/me/support
            - Method=POST,GET,PUT,PATCH,DELETE
          filters:
            - AddPrincipalToPathFilter
          metadata:
            auth-roles:
              - brand
        - id: profilePrices
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/influencers/*/prices, /api/v1/influencers/*/deals
            - Method=POST,GET,PUT,PATCH,DELETE
          filters:
            - AddPrincipalToPathPricesFilter
        - id: profiles-admin
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/influencers/*, /api/v1/brands/**
            - Method=PATCH
          metadata:
            auth-roles:
              - influencers-admin
        - id: social-media-adapter
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/influencers/me/*/followers-count, /api/v1/influencers/me/*/user-id, /api/v1/social-media-adapter/api-doc
            - Method=POST,GET
          filters:
            - AddPrincipalToPathFilter
        - id: profiles
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/influencers/*/*, /api/v1/influencers/search/**, /api/v1/brands/search/**, /api/v1/profiles/api-doc
            - Method=GET
        - id: campaign-manager
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/comments/**, /api/v1/brand-invoice/me/filter, /api/v1/brand-invoice/me/filter/**, /api/v1/fill-the-brief, /api/v1/fill-the-brief/**, /api/v1/brand-invoice/**, /api/v1/approve-brief-step/**, /api/v1/edit-campaign-brief/**, /api/v1/*/fill-the-brief, /api/v1/brief-influencers, /api/v1/brief-influencers/search/**, /api/v1/briefs, /api/v1/briefs/search/**, /api/v1/campaigns/search/**, /api/v1/pitchBrands/**, /api/v1/pitchBrands/search/**,/api/v1/pitches, /api/v1/pitches/**, /api/v1/ratings/search/**, /api/v1/campaign-manager/api-doc, /api/v1/notifications-configs-brand, /api/v1/notifications-configs-brand/**, /api/v1/notifications-configs-influencer, /api/v1/notifications-configs-influencer/**
          filters:
            - AddPrincipalToPathFilter
        - id: campaign-manager-brand
          uri: http://localhost:8086
          predicates:
            - Path= /api/v1/brand-billing-info, /api/v1/brand-billing-info/**,  /api/v1/advertising-type, /api/v1/advertising-type/**, /api/v1/campaigns/**, /api/v1/home-page/me/**, /api/v1/brief-publish-date/**,  /api/v1/campaigns/*/boost/*/*/*, /api/v1/me/brand-budget, /api/v1/brand-budget/**, /api/v1/brand-budget/**
            - Method=GET,PUT,PATCH, POST
          filters:
            - AddPrincipalToPathFilter
          metadata:
            auth-roles:
              - brand
        - id: campaign-manager-invoice
          uri: http://localhost:8086
          predicates:
            - Path= /api/v1/commands/influencers/me/count-budget-goal, /api/v1/invoice/influencer/me/**, /api/v1/influencer-invoice/**, /api/v1/invoice/**, /api/v1/billing-info/**, /api/v1/invoice/influencer/me/create
            - Method=GET,POST
          filters:
            - AddPrincipalToPathFilter
        - id: campaignsPrincipal
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/commands/me/**
            - Method=POST
          filters:
            - AddPrincipalToPathFilter
        - id: descriptions
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/*/*/description
            - Method=GET,PUT,PATCH
          filters:
            - RewritePath=/api/v1/(?<entity>.*)/(?<path>.*)/description, /api/v1/description//$\{path}/
        - id: multimedia
          uri: http://localhost:8097
          predicates:
            - Path=/api/v1/multimedia, /api/v1/multimedia-manager/**
        - id: openapi
          uri: http://localhost:8081
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /api/v1//$\{path}/api-doc
        - id: notification-service
          uri: http://localhost:9095
          predicates:
            - Path=/api/v1/notifications, /api/v1/emails, /api/v1/notification-service/api-doc
            - Method=POST
        - id: notification-service-me
          uri: http://localhost:9095
          predicates:
            - Path=/api/v1/notifications/me/device-token
            - Method=POST
          filters:
            - AddPrincipalToPathFilter
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: web
            authorization-grant-type: authorization_code
            redirect-uri: ${keycloak-client.server-url}/login/oauth2/code/keycloak
            scope: openid
        provider:
          keycloak:
            authorization-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/auth
            token-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/token
            user-info-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
            user-name-attribute: name
            user-info-authentication-method: header
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
keycloak-client:
  server-url: https://authentication-dev.theinfluencers.com/auth
  realm: influencers-com
management:
  endpoints:
    web:
      exposure:
        include: '*'

health:
  config:
    enabled: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    reactor.netty.http.client: DEBUG

springdoc:
  packages-to-scan: com.agenatech
  custom:
    ignored-routes:
      - profilesPrincipal
      - profilesDataPrincipal
      - descriptions
      - campaignsPrincipal
      - getEntitiesProfiles
      - getEntitiesCampaigns
      - openapi