server:
  port: 8081

security-constraints:
  open-uri:
    - /actuator/**
    - /api/v1/*/api-doc
    - /webjars/swagger-ui/**
    - /swagger-ui**
    - /v3/api-docs/**

cors:
  allowedOrigins: "*"
  allowedMethods: "*"
  allowedHeaders: "*"
  allowedCredentials: true
  maxAge: "3600"

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 7s
      forwarded:
        enabled: true
      x-forwarded:
        enabled: true
        forEnabled: true
        protoEnabled: true
        portEnabled: true
        prefixEnabled: true
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: false
      routes:
        - id: profilesCurrency
          uri: http://localhost:8080
          predicates: 
            - Path= /api/v1/currency, /api/v1/currency/influencer/me/convert/*/*, /api/v1/currency/influencer/me/convert/*/*, /api/v1/currency/** 
            - Method=POST,GET,PUT,PATCH,DELETE
          filters:
            - AddPrincipalToPathFilter
        - id: profilesPrincipal
          uri: http://localhost:8080
          predicates:
            - Path= /api/v1/inlfuencers/me/brands/by-name/{name}, /api/v1/information-about-each-platform, /api/v1/credits/influencer/me/accepted, /api/v1/credits/brand/me/accepted, /api/v1/credits/influencer/me/sent-or-accepted, /api/v1/credits/brand/me/sent-or-accepted, /api/v1/mood/me/today, /api/v1/mood/**, /api/v1/influencers/*/make-trusted,/api/v1/influencers/*/make-un-trusted,  /influencers/me/prices/decline-access/{brand_id}, /influencers/me/prices/approve-access/{brand_id}, /api/v1/me/platforms, /api/v1/me/platforms/all, /api/v1/access-request/**, /api/v1/access-request, /api/v1/brands/remove-premium, /api/v1/brands/make-premium, /api/v1/influencers/remove-premium, /api/v1/influencers/make-premium, /api/v1/influencers/me/access-request, /api/v1/influencers/me, /api/v1/influencers/me/followersCount, /api/v1/influencers/me/externalReferences, /api/v1/influencers/me/prices, /api/v1/influencers/me/prices/**, /api/v1/influencers/me/support, /api/v1/influencers/me/deals, /api/v1/instagram-profile, /api/v1/instagram-profile/**, /api/v1/youtube-profile, /api/v1/youtube-profile/**, /api/v1/tiktok-profile, /api/v1/tiktok-profile/**, /api/v1/snapchat-profile, /api/v1/snapchat-profile/**, /api/v1/podcasts-profile, /api/v1/podcasts-profile/**, /api/v1/brands/by-name/{name}
            - Method=GET,POST,GET,PUT,PATCH,DELETE
          filters:
            - AddPrincipalToPathFilter
        - id: profilesManagerBrands
          uri: http://localhost:8080
          predicates:
            - Path=  /api/v1/manager/me/brands, /api/v1/manager/me/brand, /api/v1/brand/me/manager, /api/v1/brand/me/manager/approve/*, /api/v1/brand/me/manager/decline/*, /api/v1/brand/manager/empty, /api/v1/brand/me/manager, /api/v1/managers, /api/v1/top-influencers
            - Method=POST,GET,PUT,PATCH,DELETE
          filters:
            - AddPrincipalToPathFilter
        - id: profiles-brand
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/brands/me, /api/v1/influencers/me/hide/profile, /api/v1/influencers/me/show/profile, /api/v1/brands/me/support, /api/v1/influencers/me/show-price-list, /api/v1/influencers/me/hide-price-list, /api/v1/influencers/*/make-trusted, /api/v1/influencers/*/make-un-trusted, /api/v1/brands/delete/me, /api/v1/influencers/delete/me
            - Method=POST,GET,PUT,PATCH,DELETE
          filters:
            - AddPrincipalToPathFilter
          metadata:
            auth-roles:
              - brand
        - id: profiles-block
          uri: http://8080
          predicates:
            - Path=/api/v1/brands/me/blocked-and-blocking-influencers, /api/v1/me/block-influencer/*, /api/v1/me/block-brand/*, /api/v1/me/unblock-influencer/*, /api/v1/me/unblock-brand/*, /api/v1/me/blocked-brands, /api/v1/me/blocked-influencers, /api/v1/me/is-influencer-blocked/*, /api/v1/me/is-brand-blocked/*, /api/v1/{firstId}/is-user-blocked/{secondId}
            - Method=GET,POST,GET,PUT,PATCH,DELETE
          filters:
            - AddPrincipalToPathFilter
        - id: profilePrices
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/influencers/*/prices, /api/v1/top-influencers, /api/v1/brands/delete/me, /api/v1/influencers/delete/me
            - Method=POST,GET,PUT,PATCH,DELETE
          filters:
            - AddPrincipalToPathPricesFilter
        - id: profiles-admin
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/influencers/*, /api/v1/brands/**, /api/v1/credits, /api/v1/credits/**
            - Method=PATCH
          metadata:
            auth-roles:
              - influencers-admin
        - id: profiles-strange-activity
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/brands/me/following-influencers, /api/v1/brands/me/unfollow/influencer/*, /api/v1/brands/me/follow/influencer/*, /api/v1/influencers/subscription-changes, /api/v1/brands/me/check-if-follow/influencers/*
            - Method=GET,PUT,PUT,POST,GET
          filters:
            - AddPrincipalToPathFilter
        - id: social-media-adapter
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/influencers/me/*/followers-count, /api/v1/influencers/me/*/user-id, /api/v1/social-media-adapter/api-doc
            - Method=POST,GET
          filters:
            - AddPrincipalToPathFilter
        - id: profiles
          uri: http://localhost:8080
          predicates:
            - Path=  /api/v1/influencer/me/app-access/ready-to-check, /api/v1/influencer/*/app-access/approve, /api/v1/influencer/*/app-access/decline, /api/v1/new-influencers, /api/v1/influencer/*/app-access/request-changes, /api/v2/chat/user, /api/v1/chat/user, /api/v1/chat/user/**, /api/v1/influencers/*/*, /api/v1/influencers/search/**, /api/v1/brands/search/**, /api/v1/profiles/api-doc, /api/v1/confirmed-influencers, /api/v1/new-brands, /api/v1/all-brands, /api/v1/brands/{brandId}/app-access/approve, /api/v1/brands/{brandId}/app-access/decline
            - Method=GET, PUT
        - id: campaign-manager
          uri: http://localhost:8086
          predicates:
            - Path= /api/v1/page-for-influencers-mood, /api/v1/page-for-influencers-mood/**, /api/v1/comparison-of-influencers, /api/v1/comments/**, /api/v1/brand-invoice/me/filter, /api/v1/brand-invoice/me/filter/**, /api/v1/fill-the-brief, /api/v1/fill-the-brief/**, /api/v1/brand-invoice/**, /api/v1/approve-brief-step/**, /api/v1/edit-campaign-brief/**, /api/v1/*/fill-the-brief, /api/v1/brief-influencers, /api/v1/brief-influencers/search/**, /api/v1/briefs, /api/v1/briefs/**, /api/v1/briefs/search/**, /api/v1/campaigns/search/**, /api/v1/pitchBrands/**, /api/v1/pitchBrands/search/**,/api/v1/pitches, /api/v1/pitches/**, /api/v1/ratings/search/**, /api/v1/campaign-manager/api-doc, /api/v1/notifications-configs-brand, /api/v1/notifications-configs-brand/**, /api/v1/notifications-configs-influencer, /api/v1/notifications-configs-influencer/**, /api/v1/campaigns/*/drafts-info, /api/v1/me/campaigns/{campaignId}/approve/{draftId}, /api/v1/me/campaigns/{campaignId}/approve-draft, /api/v1/briefs/by-dates-price, /api/v1/me/campaigns/{campaignId}/review-drafts
            - Method=GET,PUT,PATCH, POST, DELETE
          filters:
            - AddPrincipalToPathFilter
        - id: influencer-portfolio
          uri: http://localhost:8086
          predicates:
            - Path= /api/v1/campaign-statistic-access/**, /api/v1/campaign-statistic-access, /api/v1/campaign/statistic/access, /api/v1/me/campaign/statistic/access/*/approve, /api/v1/me/campaign/statistic/access/*/decline, /api/v1/portfolio/*, /api/v1/me/portfolio/campaign/*, /api/v1/advertising-types /api/v1/commands/me/notification/upload-draft/{campaignId}, /api/v1/commands/me/notification/upload-statistics/{campaignId}, /api/v1/me/search-requests
            - Method=GET,POST,PUT
          filters:
            - AddPrincipalToPathFilter
        - id: campaign-manager-brand
          uri: http://localhost:8086
          predicates:
            - Path= /api/v1/statistic/me/campaign/*/*/*, /api/v1/statistic/me/invoice/*/*/*, /api/v1/statistic/me/pitch/*/*/*, /api/v1/statistic/me/brief/*/*/*, /api/v1/brand-billing-info, /api/v1/brand-billing-info/**,  /api/v1/advertising-type, /api/v1/advertising-type/**, /api/v1/campaigns/**, /api/v1/home-page/me/**, /api/v1/brief-publish-date/**,  /api/v1/campaigns/*/boost/*/*/*, /api/v1/me/brand-budget, /api/v1/brand-budget/**, /api/v1/brand-budget/**, /api/v1/*/is-portfolio-visible, /api/v1/me/brand-budget-year/*, /api/v1/brand-budget-year, /api/v1/commands/me/generate-contract, /api/v1/commands/me/campaigns/{campaignId}/edit-contract, /api/v1/commands/me/send-contract/{contractId}, /api/v1/brands/me/get-brief-info/{briefId}
            - Method=GET,PUT,PATCH, POST
          filters:
            - AddPrincipalToPathFilter
          metadata:
            auth-roles:
              - brand
        - id: campaign-manager-invoice
          uri: http://localhost:8086
          predicates:
            - Path= /api/v1/home-page/administrator, /api/v1/campaign-youtube, /api/v1/campaign-youtube/**, /api/v1/campaign-instagram-story, /api/v1/campaign-instagram-story/**, /api/v1/campaign-instagram-post/**, /api/v1/platforms, /api/v1/platforms/**, /api/v1/instagram/webhook, /api/v1/commands/influencers/me/count-budget-goal, /api/v1/advertising-pitch-type, /api/v1/advertising-pitch-type/**, /api/v1/invoice/influencer/me/**, /api/v1/influencer-invoice/**, /api/v1/invoice/**, /api/v1/billing-info/**, /api/v1/invoice/influencer/me/create, /api/v1/invoice/influencer/me/express/create, /api/v1/home-page/find-new-campaigns-by-dates, /api/v1/home-page/find-camaigns-by-title, /api/v1/home-page/campaign-filter, /api/v1/me/campaigns-info
            - Method=GET,POST, PUT
          filters:
            - AddPrincipalToPathFilter
        - id: campaignsPrincipal
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/commands/me/**
            - Method=POST
          filters:
            - AddPrincipalToPathFilter
        - id: descriptions
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/*/*/description
            - Method=GET,PUT,PATCH
          filters:
            - RewritePath=/api/v1/(?<entity>.*)/(?<path>.*)/description, /api/v1/description//$\{path}/
        - id: multimedia
          uri: http://localhost:8097
          predicates:
            - Path=/api/v1/multimedia, /api/v1/multimedia-manager/**
        - id: openapi
          uri: http://localhost:8081
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /api/v1//$\{path}/api-doc
        - id: notification-service
          uri: http://localhost:9095
          predicates:
            - Path=/api/v1/notifications, /api/v1/emails, /api/v1/notification-service/api-doc, /api/v1/notifications/choose-influencer-mood/{userId}, /api/v1/notifications/{userId}/remove-notifications/{campaignId}/types/{type}
            - Method=POST, DELETE
        - id: notification-chat
          uri: http://localhost:9095
          predicates:
            - Path=/api/v1/chat, /api/v1/chat/{chat_id}/user/{user_id}/message/send, /api/v1/chat/{chat_id}/user/me/message/{message_id}/update, /api/v1/chat/{chat_id}/user/me/message/{message_id}/delete/{for_every_body},  /api/v1/chat/{chat_id}/user/me/read/all, /api/v1/platforms/all/*, /api/v1/chat/**, /api/v1/chat/user/{user_id}/find/brands/{name}, /api/v1/chat/{chat_id}/user/{user_id}/get-interlocutor,  /api/v1/chat/{chat_id}/user/me/mute-chat, /api/v1/chat/{chat_id}/user/me/unmute-chat
            - Method=POST, GET
          filters:
            - AddPrincipalChatToPathFilter  
        - id: notification-service-me
          uri: http://localhost:9095
          predicates:
            - Path= /api/v1/chat/generate-token/user/me, /api/v1/notifications/*/close-feedback, /api/v1/notifications/me/device-token,  /api/v1/notifications/me/notification, /api/v1/notifications/notification/mark_read, /api/v1/notifications, /api/v1/notifications/**, /api/v1/chat/{chat_id}/user/me/message/{message_id}/pin/{pinForAll}, /api/v1/chat/{chat_id}/user/me/message/{message_id}/unpin, /api/v1/chat/{chat_id}/pin/user/me, /api/v1/chat/{chat_id}/unpin/user/me, /api/v1/me/delete-device/{deviceToken}, /api/v1/notifications/{requestId}/approve-campaign-request
            - Method=POST, GET, DELETE, PUT
          filters:
            - AddPrincipalToPathFilter
        - id: key clock
          uri: https://authentication-dev.theinfluencers.com
          predicates:
            - Path= /auth/admin/realms/influencers-com/users/{user_id}/reset-password
            - Method=PUT
        - id: new-password
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/me/change-user-password, /api/v1/chats/{chatId}/users/{userId}/send-messages, /api/v1/chats/{chatId}/brands/{brandId}/send-influencer-messages
            - Method=POST
          filters:
            - AddPrincipalToPathFilter
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: web
            authorization-grant-type: authorization_code
            redirect-uri: ${keycloak-client.server-url}/login/oauth2/code/keycloak
            scope: openid
        provider:
          keycloak:
            authorization-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/auth
            token-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/token
            user-info-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
            user-name-attribute: name
            user-info-authentication-method: header
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
keycloak-client:
  server-url: https://authentication-dev.theinfluencers.com/auth
  realm: influencers-com
management:
  endpoints:
    web:
      exposure:
        include: '*'

health:
  config:
    enabled: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    reactor.netty.http.client: DEBUG

springdoc:
  packages-to-scan: com.agenatech
  custom:
    ignored-routes:
      - profilesPrincipal
      - profilesDataPrincipal
      - descriptions
      - campaignsPrincipal
      - getEntitiesProfiles
      - getEntitiesCampaigns
      - openapi
