spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
amazon:
  accessKey: '{cipher}e52a53eeafec63b1aa1838ee0d13175d7b095e803bd44dda713227c0dde73361e03198fcab22be51fd5db0b33c7c465a'
  secretKey: '{cipher}dc6ca16822eb65084ce2d3558106a0cc59064568f02ee0d3aaec5ff6604664a139a01a7289f766d0b84dbef3b246a6119cbb91dfce2b8f56cc55a6a9c03c6407'
  bucketName: influencers-dev-multimedia-manager
  region: eu-north-1
springdoc.api-docs.path: /api/v1/multimedia/api-doc
management.endpoints.web.exposure.include: '*'
logging.level:
  com.agenatech: DEBUG
health:
  config:
    enabled: false
