spring:
  datasource:
    url: jdbc:postgresql://database.cusdxsftolnc.eu-north-1.rds.amazonaws.com:5432/profiles?ssl=false
    username: postgres
    password: '{cipher}b41da68bbefacb9256bfa2b4c5d7aa96bd350716018ae08edcb837d232f985c015215920e5944ae491803fe4bcc70f15'
notifications:
  url: http://notification-service
  push-url: /api/v1/notifications
  type-url: /api/v1/notifications/{id}/change-type
  send-message: /api/v1/chat/{chat_id}/user/{user_id}/message/send
  get-interlocutor: /api/v1/chat/{chat_id}/user/{user_id}/get-interlocutor
  delete-mood-notifications: /api/v1/notifications/choose-influencer-mood/{userId}
  admin-emails: "[gladiy.pavlo@gmail.com, liubomyr.nych@gmail.com]"
campaigns:
  url: http://campaign-manager
