spring:
  datasource:
    url: jdbc:postgresql://database-dev.cusdxsftolnc.eu-north-1.rds.amazonaws.com:5432/profiles?ssl=false
    username: postgres
    password: '{cipher}80b992ff695be1018a75becadb9f8ec4d87de4d2efe673d7ed31a921d9ffe4f4508c794ed487b7268c0b410e8cc8f8ab'
notifications:
  url: http://notification-service
  push-url: /api/v1/notifications
  type-url: /api/v1/notifications/{id}/change-type
  send-message: /api/v1/chat/{chat_id}/user/{user_id}/message/send
  get-interlocutor: /api/v1/chat/{chat_id}/user/{user_id}/get-interlocutor
  delete-mood-notifications: /api/v1/notifications/choose-influencer-mood/{userId}
  admin-emails: "[gladiy.pavlo@gmail.com, liubomyr.nych@gmail.com]"
campaigns:
  url: http://campaign-manager
amazon:
  accessKey: '{cipher}25db9b1fc4d039918983700c1daf08b54bd5debd1106322582f2dec348afbce8f2aba9c6c4f65e716239499f55216aab'
  secretKey: '{cipher}038212428e96cf511f3b3011737e1da2ee47218777bd0aa1356a686adf4c2155edac82d2bfc5cba7730fc86135c65061539144a21b90912e8303030dab50e48d'
  bucketName: influencers-dev-multimedia-manager
  region: eu-north-1
auth:
  url: https://authentication-dev.theinfluencers.com/auth
  realm: influencers-com
