server:
  port: 8080
spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    datasource:
    url: jdbc:postgresql://database.cusdxsftolnc.eu-north-1.rds.amazonaws.com:5432/campaign-manager?ssl=false
    username: postgres
    password: '{cipher}3ee95f8ed1d0eb56ba38c25255992a529c0a077155cea262c5318275b0a932db48c1cbdec9acedbb3de22b27b33609ac'
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        generate_statistics: false
    show-sql: false

  accessKey: '{cipher}0a3113b95def76a420a172f647ddaee28379a50427e9157a76c66eac32cf1c0dcc9bf1d8947d9089bd1d14be6a6a9364'
  secretKey: '{cipher}69536958c74e3abea382381ad09ce841af3b7ee9fba1c3cd453d218c942656b07e3d3a51d0d23c4a7a002415c0d97dd186836b4969f85829fd7c4edaba546f90'
  bucketName: influencers-dev-multimedia-manager
  region: eu-north-1

profiles:
  url: http://profiles
notifications:
  url: http://notification-service
