server:
  port: 8080
spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    url: jdbc:postgresql://database.cusdxsftolnc.eu-north-1.rds.amazonaws.com:5432/campaign-manager?ssl=false
    username: postgres
    password: '{cipher}b41da68bbefacb9256bfa2b4c5d7aa96bd350716018ae08edcb837d232f985c015215920e5944ae491803fe4bcc70f15'
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        generate_statistics: false
    show-sql: false
amazon:
  accessKey: '{cipher}d645ad8426a13662cdb31e1456bb2e02cb0e7a60f56b1aae2058f293c81494305b8128a41c60cac6b42c2fad72e99ad2'
  secretKey: '{cipher}8436da9a30ee66b24c05cea274ce30ef4f1e6a5583c272c6ab42a90961fd8794819693e2814597b3edd4f22d35065c2dfa86dc2804fbf32dd87680227febedc8'
  bucketName: influencers-dev-multimedia-manager
  region: eu-north-1

profiles:
  url: http://profiles
  brands-by-name: /api/v1/brands/by-name/{name}
  confirmed-influencers: /api/v1/confirmed-influencers
notifications:
  url: http://notification-service
  email-url: /api/v1/emails
  push-url: /api/v1/notifications
  approve-request: /api/v1/notifications/{requestId}/approve-campaign-request
