server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://database-dev.cusdxsftolnc.eu-north-1.rds.amazonaws.com:5432/campaign-manager?ssl=false
    username: postgres
    password: '{cipher}80b992ff695be1018a75becadb9f8ec4d87de4d2efe673d7ed31a921d9ffe4f4508c794ed487b7268c0b410e8cc8f8ab'
  jpa:
    properties:
      hibernate:
        generate_statistics: false
    show-sql: false
profiles:
  url: http://profiles
notifications:
  url: http://notification-service