server:
  port: 8080
spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    datasource:
    url: jdbc:postgresql://database.cusdxsftolnc.eu-north-1.rds.amazonaws.com:5432/campaign-manager?ssl=false
    username: postgres
    password: '{cipher}f3ba777ea70a02829cf054c68c79ff3c022e2b68ff8faf538a88ff63a640def3dbb0e29e32f62d5317090fa1b03cd647'
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        generate_statistics: false
    show-sql: false
amazon:
  accessKey: '{cipher}8c3d05f29375e8cb179bff84c5d12432bbb6b66cb02bc687b753b96a49b36d9336480d2ea19c509532e3715b98c6cb15'
  secretKey: '{cipher}7bbf979805c8f81d7a27a5a693359cce3b5ff016b3a32720dba2994999bc6650603a9b51115250aaa6a297bfea3912575b303fd430f114b4b765e1025d7dc252'
  bucketName: influencers-dev-multimedia-manager
  region: eu-north-1

profiles:
  url: http://profiles
notifications:
  url: http://notification-service
